### PR TITLE
Merge changes from downstream fork

### PR DESCRIPTION
**Pull request by bsamseth**
Hi!

I have great use for this project, thank you for this initial effort. I needed to fix quite a few things for this to actually be usable in a project, and I currently maintain my fork of this project.

Based on the commit history and open issue here, it seems to me like you have stopped working on this project. I will continue to maintain my fork for as long as I need it, but this PR is meant to allow you to merge in what you want at any point.

(Some changes might not be suitable to merge (like setup.py) without modifications. I can open a clean PR with the desired changes in that case)

Ideally, if you have no intentions to go back to this project, it would be great if my fork could take over the PyPI name `jsonschema-typed`. Please contact me if that is something you'd be open to.

### CODE REVIEW

**Comment by akdor1154** [comment]
Thanks for your work in maintaining this. I have one question: (how) are you tackling runtime validation? Are you just using `jsonschema` independently in your projects?

**Comment by hound672** [comment]
@akdor1154 there is no runtime checking. This lib is just for mypy.

**Comment by bsamseth** [comment]
@akdor1154 Yes, @hound672  is correct that runtime validation is not part of the scope of this project. At runtime, all the type hints are ignored by the interpreter. To actually validate objects, you need to use `jsonschema` separately. What this project allows you to do is to greatly enhance the information available to `mypy` during static analysis, catching a whole class of potential errors otherwise impossible to catch with `mypy`.

PS: If you experience issues, have questions etc., please raise them as issues in the [downstream repo](https://github.com/inspera/jsonschema-typed) as this repository seems to be dead.

**Comment by akdor1154** [comment]
Thanks for the replies guys. I understand the point of this project, I just wondered if you'd come up with a better pattern than
```py
Foo = JSONSchema["types/Foo.json"]
with open("types/Foo.json") as schemaFile:
  fooValidator = jsonschema.Draft7Validator(schemaFile)

foo: Foo = fooValidator.validate(maybeFoo)
```
× however many schemata you have.

I can't work out how to make python aware of any association between the `Foo` type and `fooValidator`, which I think would be necessary to get rid of the above boilerplate when dealing with many types.

I think the original author managed something like this with one of their approaches.

You're also right that discussion on a dead pr is probably not the best place for this :) but @bsamseth I think you have issues/discussion disabled in your repo.

**Comment by bsamseth** [comment]
@akdor1154 Ops, somehow issues got disabled when I moved the repo. Issues are enabled now. Please move the conversation there, for any future users' benefit.

**Comment by felixvd** [comment]
@bsamseth Thanks for maintaining this project on your fork. We have moved this repository to the organization namespace https://github.com/jsonschema-typed/jsonschema-typed/ as discussed in #1 and will release `jsonschema-typed` on pypi again. I sent you an invite.

**Comment by bsamseth** [comment]
@felixvd Interesting to see this revived! Personally I haven't used this since early 2020, as I found `pydantic` to be a superior solution in all my use cases. But good luck with the project! 😊

**Comment by felixvd** [comment]
@bsamseth Thanks for the pointer. I've looked at Pydantic in my first survey, but I didn't see a way to convert from JSON schemas to models, and our definitions are already in JSONSchema, so it didn't seem like a feasible option. But maybe I missed something, so I will make sure to take another look. Cheers!

**Comment by felixvd** [comment]
@bsamseth Thanks once again for maintaining `jsonschema-typed-v2`. I just released `jsonschema-typed` with your (and my) changes. To avoid confusion, it might be good to point [jsonschema-typed-v2 on PyPI](https://pypi.org/project/jsonschema-typed-v2/) to the [original jsonschema-typed package](https://pypi.org/project/jsonschema-typed/). I'm not sure about the right procedure to do that though.

**Pull request merged**
